# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-06 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DublinFlags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('taken', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DublinOnRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat_user', models.FloatField()),
                ('lng_user', models.FloatField()),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flagsGame.DublinFlags')),
            ],
        ),
    ]
