# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-06 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flagsGame', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dublinflags',
            old_name='Lat',
            new_name='lat',
        ),
    ]
